language: python

python:
    - 2.7
    - 3.4
    - 3.5

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - SETUP_CMD='test'
        - CONDA_DEPENDENCIES=''
        - PIP_DEPENDENCIES=''

    matrix:
        - SETUP_CMD='egg_info'
        - SETUP_CMD='test'

matrix:
    include:
        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_sphinx -w'

        # Try Astropy development version
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='test --coverage'
        - python: 3.5
          env: ASTROPY_VERSION=development
        - python: 2.7
          env: ASTROPY_VERSION=lts CONDA_CHANNELS=astropy-ci-extras
        - python: 3.5
          env: ASTROPY_VERSION=lts CONDA_CHANNELS=astropy-ci-extras

        # Python 3.3 doesn't have numpy 1.10 in conda, they can be put
        # back into the main matrix once the numpy build is available in the
        # astropy-ci-extras channel (or in the one provided in the
        # CONDA_CHANNELS environmental variable).
        - python: 3.3
          env: SETUP_CMD='egg_info'
        - python: 3.3
          env: SETUP_CMD='test' NUMPY_VERSION=1.9

        # Try older numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.10
        - python: 2.7
          env: NUMPY_VERSION=1.9
        - python: 2.7
          env: NUMPY_VERSION=1.8
        - python: 2.7
          env: NUMPY_VERSION=1.7

        # Try numpy pre-release
        - python: 3.5
          env: NUMPY_VERSION=prerelease

install:
    # Installing python dependencies with conda
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

    # Build Montage from source
    - wget http://montage.ipac.caltech.edu/download/Montage_v3.3.tar.gz
    - tar zxf Montage_v3.3.tar.gz
    - cd Montage_v3.3
    - make
    - cd ..
    - export PATH=$PATH:$PWD/Montage_v3.3/bin

script:
   - python setup.py $SETUP_CMD

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='montage_wrapper/tests/coveragerc'; fi
